main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todolist.urls')),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('pw_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('signup/', views.signup, name='signup')
]

main/todolist/urls.py
from django.urls import path
from . import views


app_name = 'todolist'
urlpatterns = [
    path("", view=views.index, name="index"),
    path("del/<int:task_id>", view=views.delete, name="delete"),
    path("create_page/", view=views.create_page, name="create_page"),
    path("update/<int:task_id>", view=views.update, name="update"),
    path("create/", view=views.create, name="create"),
]

main/main/models.py
from django import forms
from django.contrib.auth.models import User
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, EmailValidator
from django.forms.widgets import EmailInput, PasswordInput
from django.contrib.auth.models import User



class SignupForm(forms.Form):
    username = forms.CharField(label="Username", max_length=30, 
                                required=True, 
                                validators=[MinLengthValidator(5)], 
                                 
                                )
    email = forms.CharField(label="Email", required=True, widget=EmailInput, validators=[EmailValidator])
    password = forms.CharField(label="Password", max_length=30, widget=PasswordInput,required=True, validators=[])
    re_password = forms.CharField(label="Confirm Password", max_length=30, widget=PasswordInput, required=True)

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).first() == None:
            return username
        else:
            raise ValidationError("Username exists")




    def clean_re_password(self):
        confirm_password = self.cleaned_data['re_password']
        original = self.cleaned_data['password']
        if confirm_password != original:
            raise ValidationError("Password Reentered Incorrectly")

        return confirm_password

main/todolist/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django import forms
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class List(models.Model):
    pass

class Task(models.Model):
    list = models.ForeignKey(List, on_delete=models.CASCADE, blank=True, null=True)
    task_name = models.CharField(max_length=200)
    done = models.BooleanField(default=False)
    pub_date = models.DateTimeField("date created", default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self) -> str:
        return self.task_name


class CreateForm(forms.Form):
    task_text = forms.CharField(max_length=100, label=False, required=True, \
                                 validators=[MinLengthValidator(3)], \
                                 widget=forms.TextInput(attrs={'placeholders': 'Enter task name...'})
                                )       

    # def clean_task_text(self):
    #     data = self.cleaned_data['task_text']

    #     # if length < 3:
    #     if len(data) < 3:
    #         raise ValidationError('Task name must be more than 3 chars!')

    #     return data

main/main/views.py
from django.http.response import HttpResponseRedirect

from django.urls import reverse
from django.contrib.auth import login as l
from django.contrib.auth import logout as lo
from .models import SignupForm
from django.contrib.auth.models import User
from django.shortcuts import render

from django.contrib import messages

def signup(r):
    if r.method == 'POST':
        username = r.POST['username']
        email = r.POST['email']
        re_password = r.POST['re_password']
        password = r.POST['password']

        form = SignupForm(r.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            email =  form.cleaned_data['email']
            password =  form.cleaned_data['password']
            User.objects.create_user(username=username, email=email, password=password)

            messages.success(r, "Registration Sucess. Please login...")

            return HttpResponseRedirect(reverse('login'))
    else:
        form = SignupForm()

    return render(r, "registration/signup.html", {'form': form})


# def login(r):
#     if r.user.is_authenticated:
#         return HttpResponseRedirect(reverse('todolist:index')) 
#     else:
#         l(r, r.user)

# def logout(r):
#     lo(r)
#     return HttpResponseRedirect(reverse('todolist:index'))

# def reset_pass(r):
#     pass

main/todolist/views.py
from django.core import exceptions
from django.http.response import Http404, HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import List, Task, CreateForm
from django.urls import reverse
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import sys
import json
# Create your views here.


@login_required
def index(request):
    form = CreateForm()
    # tasks = request.user.task_set
    tasks = Task.objects.filter(user=request.user).order_by("-pub_date")
    return render(request, "todolist/main.html", {'tasks': tasks, 'form': form})


# delete for ajax
def delete(r, task_id):
    try:
        t = Task.objects.get(pk=task_id)
        t.delete()
        loads = {'task_name': t.task_name}
        # return HttpResponse(json.dumps(loads), content_type="application/json")

        return JsonResponse(loads, status=200)

    except ObjectDoesNotExist:
        return JsonResponse({'error': "object not found", 'task_name': t.task_name }, status=404)

# def update_page(r, task_id)
#     t = get_object_or_404(Task, pk=task_id)
#     return render(r, "todolist/update.html", {"task": t})

def update(r, task_id):
    task_name = r.POST['task_name']
    print(task_name, file=sys.stderr)
    try:
        t = Task.objects.get(pk=task_id)
        t.task_name = task_name
        t.save()
        return HttpResponse(f'{task_name}')
    except ObjectDoesNotExist:
        return HttpResponseNotFound("Can not update")

def create_page(r):
    return render(r, "todolist/create.html")

def create(r):
    if r.method == "POST":
        form = CreateForm(r.POST)
        if form.is_valid():
            t = Task()
            t.task_name = form.cleaned_data['task_text']
            t.user = User.objects.get(username=r.user.username) 
            t.save()
            return HttpResponseRedirect(reverse("todolist:index"))
    
    else:
        form = CreateForm()

    tasks = Task.objects.order_by("-pub_date")
    return render(r, "todolist/main.html", {'tasks': tasks, 'form': form})

    

main/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'todolist/base.css' %}">

    {% block style %}

    {% endblock %}

    {% if title %}l 
    <title> {{ title }}</title>
    {% endif %}
</head>
<body>
    <div class="nav-bar">
        <a href="{% url 'todolist:index' %}">Home</a>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Log Out</a>
        <span>Hello, {{ user.username }}</span>
        {% else %}
            {% if request.path != "/signup/" %}
            <a href="{% url 'signup' %}">Sign Up</a>
            {% else %}
            <a href="{% url 'login' %}">Log In</a>
            {% endif %}
        {% endif %}

    </div>

    <hr>
    <div class="content">
        <div>

        {% block content %}

        {% endblock %}

        </div>


    </div> 
</body>
</html>

main/todolist/templates/todolist/create.html
<form action="{% url 'todolist:create' %}" method="post">
    {% csrf_token %}
    <label for="task_name">Task Name:</label>
    <input type="text" name="task_name" value="">
    <input type="submit" value="Create">
</form>

main/todolist/templates/todolist/main.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <script src="{% static 'todolist/main.js' %}"></script>
    <link rel="stylesheet" href="{% static 'todolist/main.css' %}">
{% endblock %}


{% block content %}

    <div class="tasks-div">
        <div class="new-task-div">
            <form action="{% url 'todolist:create' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <input id="btn_create" class="btn btn-primary" type="submit" value="New Task">
            </form>

    </div>
    {% if tasks %}
        {% for task in tasks %}
        <div class="task">
            <textarea onfocusout="updateTask(`{% url 'todolist:update' task.id %}`, this)">{{ task.task_name }}</textarea>
            <button class="btn btn-danger" onclick="delTask(`{% url 'todolist:delete' task.id %}`, this)">Delete</button>
        </div>
        {% endfor %}
    </div>

    {% else %}

    No tasks found.

    {% endif %}

    </div>
    <script>
        var httpRequest;

        document.addEventListener("DOMContentLoaded", function() {

        })

        function updateTask(endpoint, element) {
            let new_task_name = element.value.trim();
            console.log(new_task_name)
            httpRequest = new XMLHttpRequest;
            httpRequest.onreadystatechange = function() {
                postUpdate(element);
            }

            httpRequest.open("POST", endpoint)
            httpRequest.setRequestHeader("X-CSRFToken", '{{ csrf_token }}')
            httpRequest.setRequestHeader("Content-Type", "application/x-www-form-urlencoded")
            httpRequest.send(`task_name=${new_task_name}`)

        }

        function delTask(endpoint, div) {
            if (confirm("Are you sure?")) {
                httpRequest = new XMLHttpRequest();
                httpRequest.onreadystatechange = function () {
                    postDel(div)
                }
                httpRequest.open("GET", endpoint);
                // xmlhttp.setRequestHeader("Content-Type", "application/json")
                httpRequest.send()
            }
        }

        function postDel(element) {
            if (httpRequest.readyState === XMLHttpRequest.DONE) {
                let response = JSON.parse(httpRequest.responseText);
                if (httpRequest.status === 200) {

                    element.parentElement.remove();
                } else {
                    alert(`error deleting task: ${response['task_name']}`)
                }
            }
        }

        function postUpdate(element) {
            if (httpRequest.readyState === XMLHttpRequest.DONE) {
                if (httpRequest.status === 200) {
                    element.value = httpRequest.responseText;
                } else {
                    alert("Can not update!")
                }
            }
        }

    </script>
{% endblock %}